// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CellSpecApplyConfiguration represents a declarative configuration of the CellSpec type for use
// with apply.
//
// CellSpec defines the desired state of Cell
type CellSpecApplyConfiguration struct {
	NodeRef  *LocalObjectReferenceApplyConfiguration `json:"nodeRef,omitempty"`
	ID       *string                                 `json:"id,omitempty"`
	Hostname *string                                 `json:"hostname,omitempty"`
	IPs      []string                                `json:"ips,omitempty"`
	Prefixes []string                                `json:"prefixes,omitempty"`
	Peers    []PeerApplyConfiguration                `json:"peers,omitempty"`
}

// CellSpecApplyConfiguration constructs a declarative configuration of the CellSpec type for use with
// apply.
func CellSpec() *CellSpecApplyConfiguration {
	return &CellSpecApplyConfiguration{}
}

// WithNodeRef sets the NodeRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeRef field is set to the value of the last call.
func (b *CellSpecApplyConfiguration) WithNodeRef(value *LocalObjectReferenceApplyConfiguration) *CellSpecApplyConfiguration {
	b.NodeRef = value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *CellSpecApplyConfiguration) WithID(value string) *CellSpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *CellSpecApplyConfiguration) WithHostname(value string) *CellSpecApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *CellSpecApplyConfiguration) WithIPs(values ...string) *CellSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *CellSpecApplyConfiguration) WithPrefixes(values ...string) *CellSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithPeers adds the given value to the Peers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Peers field.
func (b *CellSpecApplyConfiguration) WithPeers(values ...*PeerApplyConfiguration) *CellSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPeers")
		}
		b.Peers = append(b.Peers, *values[i])
	}
	return b
}
