// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/fabric/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CellStatusApplyConfiguration represents a declarative configuration of the CellStatus type for use
// with apply.
//
// CellStatus defines the observed state of Cell.
type CellStatusApplyConfiguration struct {
	// Phase is the phase a Cell is in.
	Phase *apiv1alpha1.CellPhase `json:"phase,omitempty"`
	// Conditions represent the current state of the Cell resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// CellStatusApplyConfiguration constructs a declarative configuration of the CellStatus type for use with
// apply.
func CellStatus() *CellStatusApplyConfiguration {
	return &CellStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CellStatusApplyConfiguration) WithPhase(value apiv1alpha1.CellPhase) *CellStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CellStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *CellStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
