// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DeviceInterfaceStatusApplyConfiguration represents a declarative configuration of the DeviceInterfaceStatus type for use
// with apply.
//
// DeviceInterfaceStatus defines the observed state of DeviceInterface.
type DeviceInterfaceStatusApplyConfiguration struct {
	// OperationState is the actual operation state the interface has.
	OperationState *apiv1alpha1.OperationState `json:"operationState,omitempty"`
	// Conditions represent the current state of the DeviceInterface resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DeviceInterfaceStatusApplyConfiguration constructs a declarative configuration of the DeviceInterfaceStatus type for use with
// apply.
func DeviceInterfaceStatus() *DeviceInterfaceStatusApplyConfiguration {
	return &DeviceInterfaceStatusApplyConfiguration{}
}

// WithOperationState sets the OperationState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationState field is set to the value of the last call.
func (b *DeviceInterfaceStatusApplyConfiguration) WithOperationState(value apiv1alpha1.OperationState) *DeviceInterfaceStatusApplyConfiguration {
	b.OperationState = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DeviceInterfaceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DeviceInterfaceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
