// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DeviceSpecApplyConfiguration represents a declarative configuration of the DeviceSpec type for use
// with apply.
//
// DeviceSpec defines the desired state of Device
type DeviceSpecApplyConfiguration struct {
	// ProviderID is the provider internal ID of the device.
	ProviderID *string `json:"providerID,omitempty"`
	// SwitchRef references the active switch configuration for this device, if any.
	SwitchRef *NamespacedUIDReferenceApplyConfiguration `json:"switchRef,omitempty"`
}

// DeviceSpecApplyConfiguration constructs a declarative configuration of the DeviceSpec type for use with
// apply.
func DeviceSpec() *DeviceSpecApplyConfiguration {
	return &DeviceSpecApplyConfiguration{}
}

// WithProviderID sets the ProviderID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderID field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithProviderID(value string) *DeviceSpecApplyConfiguration {
	b.ProviderID = &value
	return b
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithSwitchRef(value *NamespacedUIDReferenceApplyConfiguration) *DeviceSpecApplyConfiguration {
	b.SwitchRef = value
	return b
}
