// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1"
)

// DeviceInterfaceSpecApplyConfiguration represents a declarative configuration of the DeviceInterfaceSpec type for use
// with apply.
//
// DeviceInterfaceSpec defines the desired state of DeviceInterface
type DeviceInterfaceSpecApplyConfiguration struct {
	// DeviceRef references the device this DeviceInterface belongs to.
	DeviceRef *LocalObjectReferenceApplyConfiguration `json:"deviceRef,omitempty"`
	// Handle is the provider specific handle of this DeviceInterface.
	Handle *string `json:"handle,omitempty"`
	// AdminState is the administrative state of the device interface.
	AdminState *apiv1alpha1.AdminState `json:"adminState,omitempty"`
}

// DeviceInterfaceSpecApplyConfiguration constructs a declarative configuration of the DeviceInterfaceSpec type for use with
// apply.
func DeviceInterfaceSpec() *DeviceInterfaceSpecApplyConfiguration {
	return &DeviceInterfaceSpecApplyConfiguration{}
}

// WithDeviceRef sets the DeviceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceRef field is set to the value of the last call.
func (b *DeviceInterfaceSpecApplyConfiguration) WithDeviceRef(value *LocalObjectReferenceApplyConfiguration) *DeviceInterfaceSpecApplyConfiguration {
	b.DeviceRef = value
	return b
}

// WithHandle sets the Handle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Handle field is set to the value of the last call.
func (b *DeviceInterfaceSpecApplyConfiguration) WithHandle(value string) *DeviceInterfaceSpecApplyConfiguration {
	b.Handle = &value
	return b
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *DeviceInterfaceSpecApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *DeviceInterfaceSpecApplyConfiguration {
	b.AdminState = &value
	return b
}
