// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostBGPPeerGroupApplyConfiguration represents a declarative configuration of the HostBGPPeerGroup type for use
// with apply.
type HostBGPPeerGroupApplyConfiguration struct {
	Name      *string                             `json:"name,omitempty"`
	Neighbors []HostBGPNeighborApplyConfiguration `json:"neighbors,omitempty"`
}

// HostBGPPeerGroupApplyConfiguration constructs a declarative configuration of the HostBGPPeerGroup type for use with
// apply.
func HostBGPPeerGroup() *HostBGPPeerGroupApplyConfiguration {
	return &HostBGPPeerGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HostBGPPeerGroupApplyConfiguration) WithName(value string) *HostBGPPeerGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithNeighbors adds the given value to the Neighbors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Neighbors field.
func (b *HostBGPPeerGroupApplyConfiguration) WithNeighbors(values ...*HostBGPNeighborApplyConfiguration) *HostBGPPeerGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNeighbors")
		}
		b.Neighbors = append(b.Neighbors, *values[i])
	}
	return b
}
