// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostBGPNeighborApplyConfiguration represents a declarative configuration of the HostBGPNeighbor type for use
// with apply.
type HostBGPNeighborApplyConfiguration struct {
	ServerInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"serverInterfaceRef,omitempty"`
}

// HostBGPNeighborApplyConfiguration constructs a declarative configuration of the HostBGPNeighbor type for use with
// apply.
func HostBGPNeighbor() *HostBGPNeighborApplyConfiguration {
	return &HostBGPNeighborApplyConfiguration{}
}

// WithServerInterfaceRef sets the ServerInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerInterfaceRef field is set to the value of the last call.
func (b *HostBGPNeighborApplyConfiguration) WithServerInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *HostBGPNeighborApplyConfiguration {
	b.ServerInterfaceRef = value
	return b
}
