// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostBGPApplyConfiguration represents a declarative configuration of the HostBGP type for use
// with apply.
type HostBGPApplyConfiguration struct {
	ASN        *int32                               `json:"asn,omitempty"`
	RouterID   *string                              `json:"routerID,omitempty"`
	PeerGroups []HostBGPPeerGroupApplyConfiguration `json:"peerGroups,omitempty"`
}

// HostBGPApplyConfiguration constructs a declarative configuration of the HostBGP type for use with
// apply.
func HostBGP() *HostBGPApplyConfiguration {
	return &HostBGPApplyConfiguration{}
}

// WithASN sets the ASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ASN field is set to the value of the last call.
func (b *HostBGPApplyConfiguration) WithASN(value int32) *HostBGPApplyConfiguration {
	b.ASN = &value
	return b
}

// WithRouterID sets the RouterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouterID field is set to the value of the last call.
func (b *HostBGPApplyConfiguration) WithRouterID(value string) *HostBGPApplyConfiguration {
	b.RouterID = &value
	return b
}

// WithPeerGroups adds the given value to the PeerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PeerGroups field.
func (b *HostBGPApplyConfiguration) WithPeerGroups(values ...*HostBGPPeerGroupApplyConfiguration) *HostBGPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPeerGroups")
		}
		b.PeerGroups = append(b.PeerGroups, *values[i])
	}
	return b
}
