// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostSpecApplyConfiguration represents a declarative configuration of the HostSpec type for use
// with apply.
//
// HostSpec defines the desired state of Host
type HostSpecApplyConfiguration struct {
	ServerRef *LocalObjectReferenceApplyConfiguration `json:"serverRef,omitempty"`
	IPs       []string                                `json:"ips,omitempty"`
	Prefixes  []string                                `json:"prefixes,omitempty"`
	BGP       *HostBGPApplyConfiguration              `json:"bgp,omitempty"`
}

// HostSpecApplyConfiguration constructs a declarative configuration of the HostSpec type for use with
// apply.
func HostSpec() *HostSpecApplyConfiguration {
	return &HostSpecApplyConfiguration{}
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *HostSpecApplyConfiguration) WithServerRef(value *LocalObjectReferenceApplyConfiguration) *HostSpecApplyConfiguration {
	b.ServerRef = value
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *HostSpecApplyConfiguration) WithIPs(values ...string) *HostSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *HostSpecApplyConfiguration) WithPrefixes(values ...string) *HostSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithBGP sets the BGP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGP field is set to the value of the last call.
func (b *HostSpecApplyConfiguration) WithBGP(value *HostBGPApplyConfiguration) *HostSpecApplyConfiguration {
	b.BGP = value
	return b
}
