// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/fabric/api/v1alpha1"
)

// InterfaceSpecApplyConfiguration represents a declarative configuration of the InterfaceSpec type for use
// with apply.
//
// InterfaceSpec defines the desired state of Interface.
type InterfaceSpecApplyConfiguration struct {
	// NodeRef references the node this interface belongs to.
	NodeRef *LocalObjectReferenceApplyConfiguration `json:"nodeRef,omitempty"`
	// Handle is the provider specific handle of this interface.
	Handle *string `json:"handle,omitempty"`
	// AdminState is the administrative state of the interface.
	AdminState *apiv1alpha1.AdminState `json:"adminState,omitempty"`
}

// InterfaceSpecApplyConfiguration constructs a declarative configuration of the InterfaceSpec type for use with
// apply.
func InterfaceSpec() *InterfaceSpecApplyConfiguration {
	return &InterfaceSpecApplyConfiguration{}
}

// WithNodeRef sets the NodeRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeRef field is set to the value of the last call.
func (b *InterfaceSpecApplyConfiguration) WithNodeRef(value *LocalObjectReferenceApplyConfiguration) *InterfaceSpecApplyConfiguration {
	b.NodeRef = value
	return b
}

// WithHandle sets the Handle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Handle field is set to the value of the last call.
func (b *InterfaceSpecApplyConfiguration) WithHandle(value string) *InterfaceSpecApplyConfiguration {
	b.Handle = &value
	return b
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *InterfaceSpecApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *InterfaceSpecApplyConfiguration {
	b.AdminState = &value
	return b
}
