// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LinkPeerApplyConfiguration represents a declarative configuration of the LinkPeer type for use
// with apply.
type LinkPeerApplyConfiguration struct {
	DeviceInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"deviceInterfaceRef,omitempty"`
	ServerInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"serverInterfaceRef,omitempty"`
}

// LinkPeerApplyConfiguration constructs a declarative configuration of the LinkPeer type for use with
// apply.
func LinkPeer() *LinkPeerApplyConfiguration {
	return &LinkPeerApplyConfiguration{}
}

// WithDeviceInterfaceRef sets the DeviceInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceInterfaceRef field is set to the value of the last call.
func (b *LinkPeerApplyConfiguration) WithDeviceInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *LinkPeerApplyConfiguration {
	b.DeviceInterfaceRef = value
	return b
}

// WithServerInterfaceRef sets the ServerInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerInterfaceRef field is set to the value of the last call.
func (b *LinkPeerApplyConfiguration) WithServerInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *LinkPeerApplyConfiguration {
	b.ServerInterfaceRef = value
	return b
}
