// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LinkEndpointApplyConfiguration represents a declarative configuration of the LinkEndpoint type for use
// with apply.
type LinkEndpointApplyConfiguration struct {
	DeviceInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"deviceInterfaceRef,omitempty"`
	ServerInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"serverInterfaceRef,omitempty"`
}

// LinkEndpointApplyConfiguration constructs a declarative configuration of the LinkEndpoint type for use with
// apply.
func LinkEndpoint() *LinkEndpointApplyConfiguration {
	return &LinkEndpointApplyConfiguration{}
}

// WithDeviceInterfaceRef sets the DeviceInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceInterfaceRef field is set to the value of the last call.
func (b *LinkEndpointApplyConfiguration) WithDeviceInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *LinkEndpointApplyConfiguration {
	b.DeviceInterfaceRef = value
	return b
}

// WithServerInterfaceRef sets the ServerInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerInterfaceRef field is set to the value of the last call.
func (b *LinkEndpointApplyConfiguration) WithServerInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *LinkEndpointApplyConfiguration {
	b.ServerInterfaceRef = value
	return b
}
