// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// NamespacedUIDReferenceApplyConfiguration represents a declarative configuration of the NamespacedUIDReference type for use
// with apply.
type NamespacedUIDReferenceApplyConfiguration struct {
	Namespace *string    `json:"namespace,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UID       *types.UID `json:"uid,omitempty"`
}

// NamespacedUIDReferenceApplyConfiguration constructs a declarative configuration of the NamespacedUIDReference type for use with
// apply.
func NamespacedUIDReference() *NamespacedUIDReferenceApplyConfiguration {
	return &NamespacedUIDReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedUIDReferenceApplyConfiguration) WithNamespace(value string) *NamespacedUIDReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedUIDReferenceApplyConfiguration) WithName(value string) *NamespacedUIDReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *NamespacedUIDReferenceApplyConfiguration) WithUID(value types.UID) *NamespacedUIDReferenceApplyConfiguration {
	b.UID = &value
	return b
}
