// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NodeSpecApplyConfiguration represents a declarative configuration of the NodeSpec type for use
// with apply.
//
// NodeSpec defines the desired state of Node
type NodeSpecApplyConfiguration struct {
	// ProviderID is the provider internal ID of the node.
	ProviderID *string `json:"providerID,omitempty"`
	// CellRef references the active Cell configuration for this Node, if any.
	CellRef *NamespacedUIDReferenceApplyConfiguration `json:"cellRef,omitempty"`
}

// NodeSpecApplyConfiguration constructs a declarative configuration of the NodeSpec type for use with
// apply.
func NodeSpec() *NodeSpecApplyConfiguration {
	return &NodeSpecApplyConfiguration{}
}

// WithProviderID sets the ProviderID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderID field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithProviderID(value string) *NodeSpecApplyConfiguration {
	b.ProviderID = &value
	return b
}

// WithCellRef sets the CellRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CellRef field is set to the value of the last call.
func (b *NodeSpecApplyConfiguration) WithCellRef(value *NamespacedUIDReferenceApplyConfiguration) *NodeSpecApplyConfiguration {
	b.CellRef = value
	return b
}
