// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PeerApplyConfiguration represents a declarative configuration of the Peer type for use
// with apply.
type PeerApplyConfiguration struct {
	InterfaceRef *LocalObjectReferenceApplyConfiguration `json:"interfaceRef,omitempty"`
	DHCPRelay    *string                                 `json:"dhcpRelay,omitempty"`
}

// PeerApplyConfiguration constructs a declarative configuration of the Peer type for use with
// apply.
func Peer() *PeerApplyConfiguration {
	return &PeerApplyConfiguration{}
}

// WithInterfaceRef sets the InterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterfaceRef field is set to the value of the last call.
func (b *PeerApplyConfiguration) WithInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *PeerApplyConfiguration {
	b.InterfaceRef = value
	return b
}

// WithDHCPRelay sets the DHCPRelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPRelay field is set to the value of the last call.
func (b *PeerApplyConfiguration) WithDHCPRelay(value string) *PeerApplyConfiguration {
	b.DHCPRelay = &value
	return b
}
