// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServerSpecApplyConfiguration represents a declarative configuration of the ServerSpec type for use
// with apply.
//
// ServerSpec defines the desired state of Server
type ServerSpecApplyConfiguration struct {
	// HostRef references the active host configuration for this Server, if any.
	HostRef *NamespacedUIDReferenceApplyConfiguration `json:"hostRef,omitempty"`
}

// ServerSpecApplyConfiguration constructs a declarative configuration of the ServerSpec type for use with
// apply.
func ServerSpec() *ServerSpecApplyConfiguration {
	return &ServerSpecApplyConfiguration{}
}

// WithHostRef sets the HostRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostRef field is set to the value of the last call.
func (b *ServerSpecApplyConfiguration) WithHostRef(value *NamespacedUIDReferenceApplyConfiguration) *ServerSpecApplyConfiguration {
	b.HostRef = value
	return b
}
