// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServerInterfaceSpecApplyConfiguration represents a declarative configuration of the ServerInterfaceSpec type for use
// with apply.
//
// ServerInterfaceSpec defines the desired state of ServerInterface
type ServerInterfaceSpecApplyConfiguration struct {
	Handle    *string                                 `json:"handle,omitempty"`
	ServerRef *LocalObjectReferenceApplyConfiguration `json:"serverRef,omitempty"`
}

// ServerInterfaceSpecApplyConfiguration constructs a declarative configuration of the ServerInterfaceSpec type for use with
// apply.
func ServerInterfaceSpec() *ServerInterfaceSpecApplyConfiguration {
	return &ServerInterfaceSpecApplyConfiguration{}
}

// WithHandle sets the Handle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Handle field is set to the value of the last call.
func (b *ServerInterfaceSpecApplyConfiguration) WithHandle(value string) *ServerInterfaceSpecApplyConfiguration {
	b.Handle = &value
	return b
}

// WithServerRef sets the ServerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerRef field is set to the value of the last call.
func (b *ServerInterfaceSpecApplyConfiguration) WithServerRef(value *LocalObjectReferenceApplyConfiguration) *ServerInterfaceSpecApplyConfiguration {
	b.ServerRef = value
	return b
}
