// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchVLANApplyConfiguration represents a declarative configuration of the SwitchVLAN type for use
// with apply.
type SwitchVLANApplyConfiguration struct {
	ID        *int32                               `json:"id,omitempty"`
	Prefix    *string                              `json:"prefix,omitempty"`
	DHCPRelay *string                              `json:"dhcpRelay,omitempty"`
	Members   []SwitchVLANMemberApplyConfiguration `json:"members,omitempty"`
}

// SwitchVLANApplyConfiguration constructs a declarative configuration of the SwitchVLAN type for use with
// apply.
func SwitchVLAN() *SwitchVLANApplyConfiguration {
	return &SwitchVLANApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithID(value int32) *SwitchVLANApplyConfiguration {
	b.ID = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithPrefix(value string) *SwitchVLANApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithDHCPRelay sets the DHCPRelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPRelay field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithDHCPRelay(value string) *SwitchVLANApplyConfiguration {
	b.DHCPRelay = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SwitchVLANApplyConfiguration) WithMembers(values ...*SwitchVLANMemberApplyConfiguration) *SwitchVLANApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}
