// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchBGPApplyConfiguration represents a declarative configuration of the SwitchBGP type for use
// with apply.
type SwitchBGPApplyConfiguration struct {
	ASN        *int32                                 `json:"asn,omitempty"`
	RouterID   *string                                `json:"routerID,omitempty"`
	PeerGroups []SwitchBGPPeerGroupApplyConfiguration `json:"peerGroups,omitempty"`
}

// SwitchBGPApplyConfiguration constructs a declarative configuration of the SwitchBGP type for use with
// apply.
func SwitchBGP() *SwitchBGPApplyConfiguration {
	return &SwitchBGPApplyConfiguration{}
}

// WithASN sets the ASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ASN field is set to the value of the last call.
func (b *SwitchBGPApplyConfiguration) WithASN(value int32) *SwitchBGPApplyConfiguration {
	b.ASN = &value
	return b
}

// WithRouterID sets the RouterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouterID field is set to the value of the last call.
func (b *SwitchBGPApplyConfiguration) WithRouterID(value string) *SwitchBGPApplyConfiguration {
	b.RouterID = &value
	return b
}

// WithPeerGroups adds the given value to the PeerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PeerGroups field.
func (b *SwitchBGPApplyConfiguration) WithPeerGroups(values ...*SwitchBGPPeerGroupApplyConfiguration) *SwitchBGPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPeerGroups")
		}
		b.PeerGroups = append(b.PeerGroups, *values[i])
	}
	return b
}
