// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchBGPPeerGroupApplyConfiguration represents a declarative configuration of the SwitchBGPPeerGroup type for use
// with apply.
type SwitchBGPPeerGroupApplyConfiguration struct {
	Name      *string                               `json:"name,omitempty"`
	Neighbors []SwitchBGPNeighborApplyConfiguration `json:"neighbors,omitempty"`
}

// SwitchBGPPeerGroupApplyConfiguration constructs a declarative configuration of the SwitchBGPPeerGroup type for use with
// apply.
func SwitchBGPPeerGroup() *SwitchBGPPeerGroupApplyConfiguration {
	return &SwitchBGPPeerGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchBGPPeerGroupApplyConfiguration) WithName(value string) *SwitchBGPPeerGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithNeighbors adds the given value to the Neighbors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Neighbors field.
func (b *SwitchBGPPeerGroupApplyConfiguration) WithNeighbors(values ...*SwitchBGPNeighborApplyConfiguration) *SwitchBGPPeerGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNeighbors")
		}
		b.Neighbors = append(b.Neighbors, *values[i])
	}
	return b
}
