// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchSpecApplyConfiguration represents a declarative configuration of the SwitchSpec type for use
// with apply.
//
// SwitchSpec defines the desired state of Switch
type SwitchSpecApplyConfiguration struct {
	DeviceRef *LocalObjectReferenceApplyConfiguration `json:"deviceRef,omitempty"`
	Hostname  *string                                 `json:"hostname,omitempty"`
	IPs       []string                                `json:"ips,omitempty"`
	Prefixes  []string                                `json:"prefixes,omitempty"`
	VLANs     []SwitchVLANApplyConfiguration          `json:"vlans,omitempty"`
	BGP       *SwitchBGPApplyConfiguration            `json:"bgp,omitempty"`
}

// SwitchSpecApplyConfiguration constructs a declarative configuration of the SwitchSpec type for use with
// apply.
func SwitchSpec() *SwitchSpecApplyConfiguration {
	return &SwitchSpecApplyConfiguration{}
}

// WithDeviceRef sets the DeviceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceRef field is set to the value of the last call.
func (b *SwitchSpecApplyConfiguration) WithDeviceRef(value *LocalObjectReferenceApplyConfiguration) *SwitchSpecApplyConfiguration {
	b.DeviceRef = value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *SwitchSpecApplyConfiguration) WithHostname(value string) *SwitchSpecApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *SwitchSpecApplyConfiguration) WithIPs(values ...string) *SwitchSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *SwitchSpecApplyConfiguration) WithPrefixes(values ...string) *SwitchSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithVLANs adds the given value to the VLANs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VLANs field.
func (b *SwitchSpecApplyConfiguration) WithVLANs(values ...*SwitchVLANApplyConfiguration) *SwitchSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVLANs")
		}
		b.VLANs = append(b.VLANs, *values[i])
	}
	return b
}

// WithBGP sets the BGP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGP field is set to the value of the last call.
func (b *SwitchSpecApplyConfiguration) WithBGP(value *SwitchBGPApplyConfiguration) *SwitchSpecApplyConfiguration {
	b.BGP = value
	return b
}
