// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchBGPNeighborApplyConfiguration represents a declarative configuration of the SwitchBGPNeighbor type for use
// with apply.
type SwitchBGPNeighborApplyConfiguration struct {
	VLANID             *int32                                  `json:"vlanID,omitempty"`
	DeviceInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"deviceInterfaceRef,omitempty"`
}

// SwitchBGPNeighborApplyConfiguration constructs a declarative configuration of the SwitchBGPNeighbor type for use with
// apply.
func SwitchBGPNeighbor() *SwitchBGPNeighborApplyConfiguration {
	return &SwitchBGPNeighborApplyConfiguration{}
}

// WithVLANID sets the VLANID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANID field is set to the value of the last call.
func (b *SwitchBGPNeighborApplyConfiguration) WithVLANID(value int32) *SwitchBGPNeighborApplyConfiguration {
	b.VLANID = &value
	return b
}

// WithDeviceInterfaceRef sets the DeviceInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceInterfaceRef field is set to the value of the last call.
func (b *SwitchBGPNeighborApplyConfiguration) WithDeviceInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *SwitchBGPNeighborApplyConfiguration {
	b.DeviceInterfaceRef = value
	return b
}
