// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchVLANMemberApplyConfiguration represents a declarative configuration of the SwitchVLANMember type for use
// with apply.
type SwitchVLANMemberApplyConfiguration struct {
	DeviceInterfaceRef *LocalObjectReferenceApplyConfiguration `json:"deviceInterfaceRef,omitempty"`
}

// SwitchVLANMemberApplyConfiguration constructs a declarative configuration of the SwitchVLANMember type for use with
// apply.
func SwitchVLANMember() *SwitchVLANMemberApplyConfiguration {
	return &SwitchVLANMemberApplyConfiguration{}
}

// WithDeviceInterfaceRef sets the DeviceInterfaceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceInterfaceRef field is set to the value of the last call.
func (b *SwitchVLANMemberApplyConfiguration) WithDeviceInterfaceRef(value *LocalObjectReferenceApplyConfiguration) *SwitchVLANMemberApplyConfiguration {
	b.DeviceInterfaceRef = value
	return b
}
