# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "fabric"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/fabric"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
