// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/wire/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=wire.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Cell"):
		return &apiv1alpha1.CellApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CellSpec"):
		return &apiv1alpha1.CellSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CellStatus"):
		return &apiv1alpha1.CellStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Interface"):
		return &apiv1alpha1.InterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InterfaceSpec"):
		return &apiv1alpha1.InterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InterfaceStatus"):
		return &apiv1alpha1.InterfaceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LocalObjectReference"):
		return &apiv1alpha1.LocalObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedUIDReference"):
		return &apiv1alpha1.NamespacedUIDReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Node"):
		return &apiv1alpha1.NodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodeSpec"):
		return &apiv1alpha1.NodeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodeStatus"):
		return &apiv1alpha1.NodeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Peer"):
		return &apiv1alpha1.PeerApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
