// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/wire/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/wire/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=wire.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Device"):
		return &apiv1alpha1.DeviceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeviceInterface"):
		return &apiv1alpha1.DeviceInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeviceInterfaceSpec"):
		return &apiv1alpha1.DeviceInterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeviceInterfaceStatus"):
		return &apiv1alpha1.DeviceInterfaceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeviceSpec"):
		return &apiv1alpha1.DeviceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeviceStatus"):
		return &apiv1alpha1.DeviceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Host"):
		return &apiv1alpha1.HostApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostBGP"):
		return &apiv1alpha1.HostBGPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostBGPNeighbor"):
		return &apiv1alpha1.HostBGPNeighborApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostBGPPeerGroup"):
		return &apiv1alpha1.HostBGPPeerGroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostSpec"):
		return &apiv1alpha1.HostSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostStatus"):
		return &apiv1alpha1.HostStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Link"):
		return &apiv1alpha1.LinkApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LinkEndpoint"):
		return &apiv1alpha1.LinkEndpointApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LocalObjectReference"):
		return &apiv1alpha1.LocalObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedUIDReference"):
		return &apiv1alpha1.NamespacedUIDReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Server"):
		return &apiv1alpha1.ServerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerInterface"):
		return &apiv1alpha1.ServerInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerInterfaceSpec"):
		return &apiv1alpha1.ServerInterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerInterfaceStatus"):
		return &apiv1alpha1.ServerInterfaceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerSpec"):
		return &apiv1alpha1.ServerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServerStatus"):
		return &apiv1alpha1.ServerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Switch"):
		return &apiv1alpha1.SwitchApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGP"):
		return &apiv1alpha1.SwitchBGPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGPNeighbor"):
		return &apiv1alpha1.SwitchBGPNeighborApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGPPeerGroup"):
		return &apiv1alpha1.SwitchBGPPeerGroupApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchSpec"):
		return &apiv1alpha1.SwitchSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchStatus"):
		return &apiv1alpha1.SwitchStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLAN"):
		return &apiv1alpha1.SwitchVLANApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANMember"):
		return &apiv1alpha1.SwitchVLANMemberApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
