// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.ironcore-dev.fabric.api.v1alpha1.AdminState
  scalar: string
- name: com.github.ironcore-dev.fabric.api.v1alpha1.Cell
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.CellSpec
    - name: status
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.CellStatus
- name: com.github.ironcore-dev.fabric.api.v1alpha1.CellPhase
  scalar: string
- name: com.github.ironcore-dev.fabric.api.v1alpha1.CellSpec
  map:
    fields:
    - name: hostname
      type:
        scalar: string
    - name: id
      type:
        scalar: string
    - name: ips
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: nodeRef
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.LocalObjectReference
    - name: peers
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.fabric.api.v1alpha1.Peer
          elementRelationship: atomic
    - name: prefixes
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: com.github.ironcore-dev.fabric.api.v1alpha1.CellStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: phase
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.CellPhase
- name: com.github.ironcore-dev.fabric.api.v1alpha1.Interface
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.InterfaceSpec
    - name: status
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.InterfaceStatus
- name: com.github.ironcore-dev.fabric.api.v1alpha1.InterfaceSpec
  map:
    fields:
    - name: adminState
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.AdminState
      default: Up
    - name: handle
      type:
        scalar: string
    - name: nodeRef
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.LocalObjectReference
- name: com.github.ironcore-dev.fabric.api.v1alpha1.InterfaceStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: operationState
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.OperationState
- name: com.github.ironcore-dev.fabric.api.v1alpha1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
- name: com.github.ironcore-dev.fabric.api.v1alpha1.NamespacedUIDReference
  map:
    fields:
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: com.github.ironcore-dev.fabric.api.v1alpha1.Node
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.NodeSpec
    - name: status
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.NodeStatus
- name: com.github.ironcore-dev.fabric.api.v1alpha1.NodeSpec
  map:
    fields:
    - name: cellRef
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.NamespacedUIDReference
    - name: providerID
      type:
        scalar: string
- name: com.github.ironcore-dev.fabric.api.v1alpha1.NodeStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
- name: com.github.ironcore-dev.fabric.api.v1alpha1.OperationState
  scalar: string
- name: com.github.ironcore-dev.fabric.api.v1alpha1.Peer
  map:
    fields:
    - name: dhcpRelay
      type:
        scalar: string
    - name: interfaceRef
      type:
        namedType: com.github.ironcore-dev.fabric.api.v1alpha1.LocalObjectReference
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
