// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/sonic/v1alpha1/sonic.proto

package sonicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WireGetInterfaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// iface is the Kubernetes DeviceInterface object name.
	Iface         string `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGetInterfaceRequest) Reset() {
	*x = WireGetInterfaceRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGetInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGetInterfaceRequest) ProtoMessage() {}

func (x *WireGetInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGetInterfaceRequest.ProtoReflect.Descriptor instead.
func (*WireGetInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{1}
}

func (x *WireGetInterfaceRequest) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

type WireGetInterfaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface_id is the SONiC-internal port identifier (e.g. "Ethernet0").
	InterfaceId   string `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGetInterfaceResponse) Reset() {
	*x = WireGetInterfaceResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGetInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGetInterfaceResponse) ProtoMessage() {}

func (x *WireGetInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGetInterfaceResponse.ProtoReflect.Descriptor instead.
func (*WireGetInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{2}
}

func (x *WireGetInterfaceResponse) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

type WireGetInterfaceStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// iface is the Kubernetes DeviceInterface object name.
	Iface         string `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGetInterfaceStateRequest) Reset() {
	*x = WireGetInterfaceStateRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGetInterfaceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGetInterfaceStateRequest) ProtoMessage() {}

func (x *WireGetInterfaceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGetInterfaceStateRequest.ProtoReflect.Descriptor instead.
func (*WireGetInterfaceStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{3}
}

func (x *WireGetInterfaceStateRequest) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

type WireGetInterfaceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUp       bool                   `protobuf:"varint,1,opt,name=admin_up,json=adminUp,proto3" json:"admin_up,omitempty"`
	OperUp        bool                   `protobuf:"varint,2,opt,name=oper_up,json=operUp,proto3" json:"oper_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGetInterfaceStateResponse) Reset() {
	*x = WireGetInterfaceStateResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGetInterfaceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGetInterfaceStateResponse) ProtoMessage() {}

func (x *WireGetInterfaceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGetInterfaceStateResponse.ProtoReflect.Descriptor instead.
func (*WireGetInterfaceStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{4}
}

func (x *WireGetInterfaceStateResponse) GetAdminUp() bool {
	if x != nil {
		return x.AdminUp
	}
	return false
}

func (x *WireGetInterfaceStateResponse) GetOperUp() bool {
	if x != nil {
		return x.OperUp
	}
	return false
}

type WireSetInterfaceAdminStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// iface is the Kubernetes DeviceInterface object name.
	Iface         string `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	AdminState    bool   `protobuf:"varint,2,opt,name=admin_state,json=adminState,proto3" json:"admin_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSetInterfaceAdminStateRequest) Reset() {
	*x = WireSetInterfaceAdminStateRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSetInterfaceAdminStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSetInterfaceAdminStateRequest) ProtoMessage() {}

func (x *WireSetInterfaceAdminStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSetInterfaceAdminStateRequest.ProtoReflect.Descriptor instead.
func (*WireSetInterfaceAdminStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{5}
}

func (x *WireSetInterfaceAdminStateRequest) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *WireSetInterfaceAdminStateRequest) GetAdminState() bool {
	if x != nil {
		return x.AdminState
	}
	return false
}

type WireSetInterfaceAdminStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireSetInterfaceAdminStateResponse) Reset() {
	*x = WireSetInterfaceAdminStateResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireSetInterfaceAdminStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireSetInterfaceAdminStateResponse) ProtoMessage() {}

func (x *WireSetInterfaceAdminStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireSetInterfaceAdminStateResponse.ProtoReflect.Descriptor instead.
func (*WireSetInterfaceAdminStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{6}
}

type ListInterfacesRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequestV2) Reset() {
	*x = ListInterfacesRequestV2{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequestV2) ProtoMessage() {}

func (x *ListInterfacesRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequestV2.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{7}
}

type ListInterfacesResponseV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interfaces is the list of interface names (e.g. "Ethernet0", "Ethernet4").
	Interfaces    []string `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponseV2) Reset() {
	*x = ListInterfacesResponseV2{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponseV2) ProtoMessage() {}

func (x *ListInterfacesResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponseV2.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{8}
}

func (x *ListInterfacesResponseV2) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type ApplySwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Config        *SwitchConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySwitchRequest) Reset() {
	*x = ApplySwitchRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySwitchRequest) ProtoMessage() {}

func (x *ApplySwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySwitchRequest.ProtoReflect.Descriptor instead.
func (*ApplySwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{9}
}

func (x *ApplySwitchRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ApplySwitchRequest) GetConfig() *SwitchConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ApplySwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplySwitchResponse) Reset() {
	*x = ApplySwitchResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySwitchResponse) ProtoMessage() {}

func (x *ApplySwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySwitchResponse.ProtoReflect.Descriptor instead.
func (*ApplySwitchResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{10}
}

type DeleteSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSwitchRequest) Reset() {
	*x = DeleteSwitchRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSwitchRequest) ProtoMessage() {}

func (x *DeleteSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSwitchRequest.ProtoReflect.Descriptor instead.
func (*DeleteSwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSwitchRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type DeleteSwitchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state is "" when reprovision is complete, "Reprovisioning" while in progress.
	State         string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSwitchResponse) Reset() {
	*x = DeleteSwitchResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSwitchResponse) ProtoMessage() {}

func (x *DeleteSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSwitchResponse.ProtoReflect.Descriptor instead.
func (*DeleteSwitchResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSwitchResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetCellStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellStatusRequest) Reset() {
	*x = GetCellStatusRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellStatusRequest) ProtoMessage() {}

func (x *GetCellStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCellStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{13}
}

func (x *GetCellStatusRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

// GetCellStatusResponse reports the provisioning state last written by ApplySwitch.
// state is "Creating", "Active", "Error", or "" (key absent — cell not yet provisioned).
type GetCellStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellStatusResponse) Reset() {
	*x = GetCellStatusResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellStatusResponse) ProtoMessage() {}

func (x *GetCellStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCellStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{14}
}

func (x *GetCellStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetCellStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SwitchConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *SwitchMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hostname string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// loopback_ips are CIDR prefixes for the loopback interface (e.g. "fd00::1/128").
	LoopbackIps []string `protobuf:"bytes,3,rep,name=loopback_ips,json=loopbackIps,proto3" json:"loopback_ips,omitempty"`
	// prefixes are advertised IP prefixes (e.g. "fd00::/64").
	Prefixes []string `protobuf:"bytes,4,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	Vlans    []*VLAN  `protobuf:"bytes,5,rep,name=vlans,proto3" json:"vlans,omitempty"`
	// bgp is optional; omit when BGP is not configured.
	Bgp           *BGPConfig `protobuf:"bytes,6,opt,name=bgp,proto3" json:"bgp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchConfig) Reset() {
	*x = SwitchConfig{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchConfig) ProtoMessage() {}

func (x *SwitchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchConfig.ProtoReflect.Descriptor instead.
func (*SwitchConfig) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{15}
}

func (x *SwitchConfig) GetMetadata() *SwitchMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SwitchConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SwitchConfig) GetLoopbackIps() []string {
	if x != nil {
		return x.LoopbackIps
	}
	return nil
}

func (x *SwitchConfig) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *SwitchConfig) GetVlans() []*VLAN {
	if x != nil {
		return x.Vlans
	}
	return nil
}

func (x *SwitchConfig) GetBgp() *BGPConfig {
	if x != nil {
		return x.Bgp
	}
	return nil
}

type SwitchMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchMetadata) Reset() {
	*x = SwitchMetadata{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchMetadata) ProtoMessage() {}

func (x *SwitchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchMetadata.ProtoReflect.Descriptor instead.
func (*SwitchMetadata) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{16}
}

func (x *SwitchMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SwitchMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SwitchMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type VLAN struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// prefix is the CIDR subnet for this VLAN (e.g. "fd00::1:1/80").
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// dhcp_relay is the DHCP relay IP; empty means no relay.
	DhcpRelay     string        `protobuf:"bytes,3,opt,name=dhcp_relay,json=dhcpRelay,proto3" json:"dhcp_relay,omitempty"`
	Members       []*VLANMember `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLAN) Reset() {
	*x = VLAN{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLAN) ProtoMessage() {}

func (x *VLAN) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLAN.ProtoReflect.Descriptor instead.
func (*VLAN) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{17}
}

func (x *VLAN) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VLAN) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *VLAN) GetDhcpRelay() string {
	if x != nil {
		return x.DhcpRelay
	}
	return ""
}

func (x *VLAN) GetMembers() []*VLANMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type VLANMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface_id is the SONiC-internal port identifier (e.g. "Ethernet0").
	InterfaceId   string `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLANMember) Reset() {
	*x = VLANMember{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLANMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLANMember) ProtoMessage() {}

func (x *VLANMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLANMember.ProtoReflect.Descriptor instead.
func (*VLANMember) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{18}
}

func (x *VLANMember) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

type BGPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	PeerGroups    []*BGPPeerGroup        `protobuf:"bytes,3,rep,name=peer_groups,json=peerGroups,proto3" json:"peer_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BGPConfig) Reset() {
	*x = BGPConfig{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPConfig) ProtoMessage() {}

func (x *BGPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPConfig.ProtoReflect.Descriptor instead.
func (*BGPConfig) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{19}
}

func (x *BGPConfig) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *BGPConfig) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *BGPConfig) GetPeerGroups() []*BGPPeerGroup {
	if x != nil {
		return x.PeerGroups
	}
	return nil
}

type BGPPeerGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Neighbors     []*BGPNeighbor         `protobuf:"bytes,2,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BGPPeerGroup) Reset() {
	*x = BGPPeerGroup{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPPeerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPPeerGroup) ProtoMessage() {}

func (x *BGPPeerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPPeerGroup.ProtoReflect.Descriptor instead.
func (*BGPPeerGroup) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{20}
}

func (x *BGPPeerGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BGPPeerGroup) GetNeighbors() []*BGPNeighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type BGPNeighbor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// vlan_id is set when the neighbor is VLAN-based.
	VlanId int32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// interface_id is the SONiC-internal port or VLAN interface (e.g. "Ethernet108", "Vlan1001").
	InterfaceId   string `protobuf:"bytes,2,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BGPNeighbor) Reset() {
	*x = BGPNeighbor{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPNeighbor) ProtoMessage() {}

func (x *BGPNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPNeighbor.ProtoReflect.Descriptor instead.
func (*BGPNeighbor) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{21}
}

func (x *BGPNeighbor) GetVlanId() int32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *BGPNeighbor) GetInterfaceId() string {
	if x != nil {
		return x.InterfaceId
	}
	return ""
}

type FactoryResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactoryResetRequest) Reset() {
	*x = FactoryResetRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactoryResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactoryResetRequest) ProtoMessage() {}

func (x *FactoryResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactoryResetRequest.ProtoReflect.Descriptor instead.
func (*FactoryResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{22}
}

type FactoryResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactoryResetResponse) Reset() {
	*x = FactoryResetResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactoryResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactoryResetResponse) ProtoMessage() {}

func (x *FactoryResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactoryResetResponse.ProtoReflect.Descriptor instead.
func (*FactoryResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{23}
}

func (x *FactoryResetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadinessRequest) Reset() {
	*x = GetReadinessRequest{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadinessRequest) ProtoMessage() {}

func (x *GetReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadinessRequest.ProtoReflect.Descriptor instead.
func (*GetReadinessRequest) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{24}
}

// ready is true when the agent is up and all required host-service modules are responding.
type GetReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadinessResponse) Reset() {
	*x = GetReadinessResponse{}
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadinessResponse) ProtoMessage() {}

func (x *GetReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sonic_v1alpha1_sonic_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadinessResponse.ProtoReflect.Descriptor instead.
func (*GetReadinessResponse) Descriptor() ([]byte, []int) {
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP(), []int{25}
}

func (x *GetReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_proto_sonic_v1alpha1_sonic_proto protoreflect.FileDescriptor

const file_proto_sonic_v1alpha1_sonic_proto_rawDesc = "" +
	"\n" +
	" proto/sonic/v1alpha1/sonic.proto\x12\x0eswitchagent.v1\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x17WireGetInterfaceRequest\x12\x14\n" +
	"\x05iface\x18\x01 \x01(\tR\x05iface\"=\n" +
	"\x18WireGetInterfaceResponse\x12!\n" +
	"\finterface_id\x18\x01 \x01(\tR\vinterfaceId\"4\n" +
	"\x1cWireGetInterfaceStateRequest\x12\x14\n" +
	"\x05iface\x18\x01 \x01(\tR\x05iface\"S\n" +
	"\x1dWireGetInterfaceStateResponse\x12\x19\n" +
	"\badmin_up\x18\x01 \x01(\bR\aadminUp\x12\x17\n" +
	"\aoper_up\x18\x02 \x01(\bR\x06operUp\"Z\n" +
	"!WireSetInterfaceAdminStateRequest\x12\x14\n" +
	"\x05iface\x18\x01 \x01(\tR\x05iface\x12\x1f\n" +
	"\vadmin_state\x18\x02 \x01(\bR\n" +
	"adminState\"$\n" +
	"\"WireSetInterfaceAdminStateResponse\"\x19\n" +
	"\x17ListInterfacesRequestV2\":\n" +
	"\x18ListInterfacesResponseV2\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\tR\n" +
	"interfaces\"b\n" +
	"\x12ApplySwitchRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.switchagent.v1.SwitchConfigR\x06config\"\x15\n" +
	"\x13ApplySwitchResponse\"-\n" +
	"\x13DeleteSwitchRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\",\n" +
	"\x14DeleteSwitchResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\".\n" +
	"\x14GetCellStatusRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"G\n" +
	"\x15GetCellStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfe\x01\n" +
	"\fSwitchConfig\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.switchagent.v1.SwitchMetadataR\bmetadata\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\floopback_ips\x18\x03 \x03(\tR\vloopbackIps\x12\x1a\n" +
	"\bprefixes\x18\x04 \x03(\tR\bprefixes\x12*\n" +
	"\x05vlans\x18\x05 \x03(\v2\x14.switchagent.v1.VLANR\x05vlans\x12+\n" +
	"\x03bgp\x18\x06 \x01(\v2\x19.switchagent.v1.BGPConfigR\x03bgp\"T\n" +
	"\x0eSwitchMetadata\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\"\x83\x01\n" +
	"\x04VLAN\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"dhcp_relay\x18\x03 \x01(\tR\tdhcpRelay\x124\n" +
	"\amembers\x18\x04 \x03(\v2\x1a.switchagent.v1.VLANMemberR\amembers\"/\n" +
	"\n" +
	"VLANMember\x12!\n" +
	"\finterface_id\x18\x01 \x01(\tR\vinterfaceId\"y\n" +
	"\tBGPConfig\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x12=\n" +
	"\vpeer_groups\x18\x03 \x03(\v2\x1c.switchagent.v1.BGPPeerGroupR\n" +
	"peerGroups\"]\n" +
	"\fBGPPeerGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\tneighbors\x18\x02 \x03(\v2\x1b.switchagent.v1.BGPNeighborR\tneighbors\"I\n" +
	"\vBGPNeighbor\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\x05R\x06vlanId\x12!\n" +
	"\finterface_id\x18\x02 \x01(\tR\vinterfaceId\"\x15\n" +
	"\x13FactoryResetRequest\"F\n" +
	"\x14FactoryResetResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.switchagent.v1.StatusR\x06status\"\x15\n" +
	"\x13GetReadinessRequest\",\n" +
	"\x14GetReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready2\xe4\x05\n" +
	"\x16WireSonicSwitchService\x12a\n" +
	"\fGetInterface\x12'.switchagent.v1.WireGetInterfaceRequest\x1a(.switchagent.v1.WireGetInterfaceResponse\x12p\n" +
	"\x11GetInterfaceState\x12,.switchagent.v1.WireGetInterfaceStateRequest\x1a-.switchagent.v1.WireGetInterfaceStateResponse\x12\x7f\n" +
	"\x16SetInterfaceAdminState\x121.switchagent.v1.WireSetInterfaceAdminStateRequest\x1a2.switchagent.v1.WireSetInterfaceAdminStateResponse\x12c\n" +
	"\x0eListInterfaces\x12'.switchagent.v1.ListInterfacesRequestV2\x1a(.switchagent.v1.ListInterfacesResponseV2\x12V\n" +
	"\vApplySwitch\x12\".switchagent.v1.ApplySwitchRequest\x1a#.switchagent.v1.ApplySwitchResponse\x12Y\n" +
	"\fDeleteSwitch\x12#.switchagent.v1.DeleteSwitchRequest\x1a$.switchagent.v1.DeleteSwitchResponse\x12\\\n" +
	"\rGetCellStatus\x12$.switchagent.v1.GetCellStatusRequest\x1a%.switchagent.v1.GetCellStatusResponse2\xca\x01\n" +
	"\x12SwitchAgentService\x12Y\n" +
	"\fFactoryReset\x12#.switchagent.v1.FactoryResetRequest\x1a$.switchagent.v1.FactoryResetResponse\x12Y\n" +
	"\fGetReadiness\x12#.switchagent.v1.GetReadinessRequest\x1a$.switchagent.v1.GetReadinessResponseB,Z*github.com/ironcore-dev/fabric/sonic/sonicpbb\x06proto3"

var (
	file_proto_sonic_v1alpha1_sonic_proto_rawDescOnce sync.Once
	file_proto_sonic_v1alpha1_sonic_proto_rawDescData []byte
)

func file_proto_sonic_v1alpha1_sonic_proto_rawDescGZIP() []byte {
	file_proto_sonic_v1alpha1_sonic_proto_rawDescOnce.Do(func() {
		file_proto_sonic_v1alpha1_sonic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sonic_v1alpha1_sonic_proto_rawDesc), len(file_proto_sonic_v1alpha1_sonic_proto_rawDesc)))
	})
	return file_proto_sonic_v1alpha1_sonic_proto_rawDescData
}

var file_proto_sonic_v1alpha1_sonic_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_sonic_v1alpha1_sonic_proto_goTypes = []any{
	(*Status)(nil),                             // 0: switchagent.v1.Status
	(*WireGetInterfaceRequest)(nil),            // 1: switchagent.v1.WireGetInterfaceRequest
	(*WireGetInterfaceResponse)(nil),           // 2: switchagent.v1.WireGetInterfaceResponse
	(*WireGetInterfaceStateRequest)(nil),       // 3: switchagent.v1.WireGetInterfaceStateRequest
	(*WireGetInterfaceStateResponse)(nil),      // 4: switchagent.v1.WireGetInterfaceStateResponse
	(*WireSetInterfaceAdminStateRequest)(nil),  // 5: switchagent.v1.WireSetInterfaceAdminStateRequest
	(*WireSetInterfaceAdminStateResponse)(nil), // 6: switchagent.v1.WireSetInterfaceAdminStateResponse
	(*ListInterfacesRequestV2)(nil),            // 7: switchagent.v1.ListInterfacesRequestV2
	(*ListInterfacesResponseV2)(nil),           // 8: switchagent.v1.ListInterfacesResponseV2
	(*ApplySwitchRequest)(nil),                 // 9: switchagent.v1.ApplySwitchRequest
	(*ApplySwitchResponse)(nil),                // 10: switchagent.v1.ApplySwitchResponse
	(*DeleteSwitchRequest)(nil),                // 11: switchagent.v1.DeleteSwitchRequest
	(*DeleteSwitchResponse)(nil),               // 12: switchagent.v1.DeleteSwitchResponse
	(*GetCellStatusRequest)(nil),               // 13: switchagent.v1.GetCellStatusRequest
	(*GetCellStatusResponse)(nil),              // 14: switchagent.v1.GetCellStatusResponse
	(*SwitchConfig)(nil),                       // 15: switchagent.v1.SwitchConfig
	(*SwitchMetadata)(nil),                     // 16: switchagent.v1.SwitchMetadata
	(*VLAN)(nil),                               // 17: switchagent.v1.VLAN
	(*VLANMember)(nil),                         // 18: switchagent.v1.VLANMember
	(*BGPConfig)(nil),                          // 19: switchagent.v1.BGPConfig
	(*BGPPeerGroup)(nil),                       // 20: switchagent.v1.BGPPeerGroup
	(*BGPNeighbor)(nil),                        // 21: switchagent.v1.BGPNeighbor
	(*FactoryResetRequest)(nil),                // 22: switchagent.v1.FactoryResetRequest
	(*FactoryResetResponse)(nil),               // 23: switchagent.v1.FactoryResetResponse
	(*GetReadinessRequest)(nil),                // 24: switchagent.v1.GetReadinessRequest
	(*GetReadinessResponse)(nil),               // 25: switchagent.v1.GetReadinessResponse
}
var file_proto_sonic_v1alpha1_sonic_proto_depIdxs = []int32{
	15, // 0: switchagent.v1.ApplySwitchRequest.config:type_name -> switchagent.v1.SwitchConfig
	16, // 1: switchagent.v1.SwitchConfig.metadata:type_name -> switchagent.v1.SwitchMetadata
	17, // 2: switchagent.v1.SwitchConfig.vlans:type_name -> switchagent.v1.VLAN
	19, // 3: switchagent.v1.SwitchConfig.bgp:type_name -> switchagent.v1.BGPConfig
	18, // 4: switchagent.v1.VLAN.members:type_name -> switchagent.v1.VLANMember
	20, // 5: switchagent.v1.BGPConfig.peer_groups:type_name -> switchagent.v1.BGPPeerGroup
	21, // 6: switchagent.v1.BGPPeerGroup.neighbors:type_name -> switchagent.v1.BGPNeighbor
	0,  // 7: switchagent.v1.FactoryResetResponse.status:type_name -> switchagent.v1.Status
	1,  // 8: switchagent.v1.WireSonicSwitchService.GetInterface:input_type -> switchagent.v1.WireGetInterfaceRequest
	3,  // 9: switchagent.v1.WireSonicSwitchService.GetInterfaceState:input_type -> switchagent.v1.WireGetInterfaceStateRequest
	5,  // 10: switchagent.v1.WireSonicSwitchService.SetInterfaceAdminState:input_type -> switchagent.v1.WireSetInterfaceAdminStateRequest
	7,  // 11: switchagent.v1.WireSonicSwitchService.ListInterfaces:input_type -> switchagent.v1.ListInterfacesRequestV2
	9,  // 12: switchagent.v1.WireSonicSwitchService.ApplySwitch:input_type -> switchagent.v1.ApplySwitchRequest
	11, // 13: switchagent.v1.WireSonicSwitchService.DeleteSwitch:input_type -> switchagent.v1.DeleteSwitchRequest
	13, // 14: switchagent.v1.WireSonicSwitchService.GetCellStatus:input_type -> switchagent.v1.GetCellStatusRequest
	22, // 15: switchagent.v1.SwitchAgentService.FactoryReset:input_type -> switchagent.v1.FactoryResetRequest
	24, // 16: switchagent.v1.SwitchAgentService.GetReadiness:input_type -> switchagent.v1.GetReadinessRequest
	2,  // 17: switchagent.v1.WireSonicSwitchService.GetInterface:output_type -> switchagent.v1.WireGetInterfaceResponse
	4,  // 18: switchagent.v1.WireSonicSwitchService.GetInterfaceState:output_type -> switchagent.v1.WireGetInterfaceStateResponse
	6,  // 19: switchagent.v1.WireSonicSwitchService.SetInterfaceAdminState:output_type -> switchagent.v1.WireSetInterfaceAdminStateResponse
	8,  // 20: switchagent.v1.WireSonicSwitchService.ListInterfaces:output_type -> switchagent.v1.ListInterfacesResponseV2
	10, // 21: switchagent.v1.WireSonicSwitchService.ApplySwitch:output_type -> switchagent.v1.ApplySwitchResponse
	12, // 22: switchagent.v1.WireSonicSwitchService.DeleteSwitch:output_type -> switchagent.v1.DeleteSwitchResponse
	14, // 23: switchagent.v1.WireSonicSwitchService.GetCellStatus:output_type -> switchagent.v1.GetCellStatusResponse
	23, // 24: switchagent.v1.SwitchAgentService.FactoryReset:output_type -> switchagent.v1.FactoryResetResponse
	25, // 25: switchagent.v1.SwitchAgentService.GetReadiness:output_type -> switchagent.v1.GetReadinessResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_sonic_v1alpha1_sonic_proto_init() }
func file_proto_sonic_v1alpha1_sonic_proto_init() {
	if File_proto_sonic_v1alpha1_sonic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sonic_v1alpha1_sonic_proto_rawDesc), len(file_proto_sonic_v1alpha1_sonic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_sonic_v1alpha1_sonic_proto_goTypes,
		DependencyIndexes: file_proto_sonic_v1alpha1_sonic_proto_depIdxs,
		MessageInfos:      file_proto_sonic_v1alpha1_sonic_proto_msgTypes,
	}.Build()
	File_proto_sonic_v1alpha1_sonic_proto = out.File
	file_proto_sonic_v1alpha1_sonic_proto_goTypes = nil
	file_proto_sonic_v1alpha1_sonic_proto_depIdxs = nil
}
