// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/sonic/v1alpha1/sonic.proto

package sonicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireSonicSwitchService_GetInterface_FullMethodName           = "/switchagent.v1.WireSonicSwitchService/GetInterface"
	WireSonicSwitchService_GetInterfaceState_FullMethodName      = "/switchagent.v1.WireSonicSwitchService/GetInterfaceState"
	WireSonicSwitchService_SetInterfaceAdminState_FullMethodName = "/switchagent.v1.WireSonicSwitchService/SetInterfaceAdminState"
	WireSonicSwitchService_ListInterfaces_FullMethodName         = "/switchagent.v1.WireSonicSwitchService/ListInterfaces"
	WireSonicSwitchService_ApplySwitch_FullMethodName            = "/switchagent.v1.WireSonicSwitchService/ApplySwitch"
	WireSonicSwitchService_DeleteSwitch_FullMethodName           = "/switchagent.v1.WireSonicSwitchService/DeleteSwitch"
	WireSonicSwitchService_GetCellStatus_FullMethodName          = "/switchagent.v1.WireSonicSwitchService/GetCellStatus"
)

// WireSonicSwitchServiceClient is the client API for WireSonicSwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WireSonicSwitchServiceClient interface {
	GetInterface(ctx context.Context, in *WireGetInterfaceRequest, opts ...grpc.CallOption) (*WireGetInterfaceResponse, error)
	GetInterfaceState(ctx context.Context, in *WireGetInterfaceStateRequest, opts ...grpc.CallOption) (*WireGetInterfaceStateResponse, error)
	SetInterfaceAdminState(ctx context.Context, in *WireSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*WireSetInterfaceAdminStateResponse, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error)
	ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error)
	DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error)
	GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error)
}

type wireSonicSwitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireSonicSwitchServiceClient(cc grpc.ClientConnInterface) WireSonicSwitchServiceClient {
	return &wireSonicSwitchServiceClient{cc}
}

func (c *wireSonicSwitchServiceClient) GetInterface(ctx context.Context, in *WireGetInterfaceRequest, opts ...grpc.CallOption) (*WireGetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireGetInterfaceResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) GetInterfaceState(ctx context.Context, in *WireGetInterfaceStateRequest, opts ...grpc.CallOption) (*WireGetInterfaceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireGetInterfaceStateResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetInterfaceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) SetInterfaceAdminState(ctx context.Context, in *WireSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*WireSetInterfaceAdminStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireSetInterfaceAdminStateResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_SetInterfaceAdminState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponseV2)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySwitchResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_ApplySwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSwitchResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_DeleteSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellStatusResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetCellStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireSonicSwitchServiceServer is the server API for WireSonicSwitchService service.
// All implementations must embed UnimplementedWireSonicSwitchServiceServer
// for forward compatibility.
type WireSonicSwitchServiceServer interface {
	GetInterface(context.Context, *WireGetInterfaceRequest) (*WireGetInterfaceResponse, error)
	GetInterfaceState(context.Context, *WireGetInterfaceStateRequest) (*WireGetInterfaceStateResponse, error)
	SetInterfaceAdminState(context.Context, *WireSetInterfaceAdminStateRequest) (*WireSetInterfaceAdminStateResponse, error)
	ListInterfaces(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error)
	ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error)
	DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error)
	GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error)
	mustEmbedUnimplementedWireSonicSwitchServiceServer()
}

// UnimplementedWireSonicSwitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireSonicSwitchServiceServer struct{}

func (UnimplementedWireSonicSwitchServiceServer) GetInterface(context.Context, *WireGetInterfaceRequest) (*WireGetInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) GetInterfaceState(context.Context, *WireGetInterfaceStateRequest) (*WireGetInterfaceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterfaceState not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) SetInterfaceAdminState(context.Context, *WireSetInterfaceAdminStateRequest) (*WireSetInterfaceAdminStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInterfaceAdminState not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) ListInterfaces(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySwitch not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSwitch not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCellStatus not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) mustEmbedUnimplementedWireSonicSwitchServiceServer() {
}
func (UnimplementedWireSonicSwitchServiceServer) testEmbeddedByValue() {}

// UnsafeWireSonicSwitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireSonicSwitchServiceServer will
// result in compilation errors.
type UnsafeWireSonicSwitchServiceServer interface {
	mustEmbedUnimplementedWireSonicSwitchServiceServer()
}

func RegisterWireSonicSwitchServiceServer(s grpc.ServiceRegistrar, srv WireSonicSwitchServiceServer) {
	// If the following call pancis, it indicates UnimplementedWireSonicSwitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireSonicSwitchService_ServiceDesc, srv)
}

func _WireSonicSwitchService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetInterface(ctx, req.(*WireGetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_GetInterfaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetInterfaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetInterfaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetInterfaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetInterfaceState(ctx, req.(*WireGetInterfaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_SetInterfaceAdminState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireSetInterfaceAdminStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).SetInterfaceAdminState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_SetInterfaceAdminState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).SetInterfaceAdminState(ctx, req.(*WireSetInterfaceAdminStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_ApplySwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).ApplySwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_ApplySwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).ApplySwitch(ctx, req.(*ApplySwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_DeleteSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).DeleteSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_DeleteSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).DeleteSwitch(ctx, req.(*DeleteSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_GetCellStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetCellStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetCellStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetCellStatus(ctx, req.(*GetCellStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireSonicSwitchService_ServiceDesc is the grpc.ServiceDesc for WireSonicSwitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireSonicSwitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.WireSonicSwitchService",
	HandlerType: (*WireSonicSwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterface",
			Handler:    _WireSonicSwitchService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceState",
			Handler:    _WireSonicSwitchService_GetInterfaceState_Handler,
		},
		{
			MethodName: "SetInterfaceAdminState",
			Handler:    _WireSonicSwitchService_SetInterfaceAdminState_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _WireSonicSwitchService_ListInterfaces_Handler,
		},
		{
			MethodName: "ApplySwitch",
			Handler:    _WireSonicSwitchService_ApplySwitch_Handler,
		},
		{
			MethodName: "DeleteSwitch",
			Handler:    _WireSonicSwitchService_DeleteSwitch_Handler,
		},
		{
			MethodName: "GetCellStatus",
			Handler:    _WireSonicSwitchService_GetCellStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sonic/v1alpha1/sonic.proto",
}

const (
	SwitchAgentService_FactoryReset_FullMethodName = "/switchagent.v1.SwitchAgentService/FactoryReset"
	SwitchAgentService_GetReadiness_FullMethodName = "/switchagent.v1.SwitchAgentService/GetReadiness"
)

// SwitchAgentServiceClient is the client API for SwitchAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwitchAgentServiceClient interface {
	FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error)
	GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error)
}

type switchAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchAgentServiceClient(cc grpc.ClientConnInterface) SwitchAgentServiceClient {
	return &switchAgentServiceClient{cc}
}

func (c *switchAgentServiceClient) FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryResetResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadinessResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchAgentServiceServer is the server API for SwitchAgentService service.
// All implementations must embed UnimplementedSwitchAgentServiceServer
// for forward compatibility.
type SwitchAgentServiceServer interface {
	FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error)
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

// UnimplementedSwitchAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchAgentServiceServer struct{}

func (UnimplementedSwitchAgentServiceServer) FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReadiness not implemented")
}
func (UnimplementedSwitchAgentServiceServer) mustEmbedUnimplementedSwitchAgentServiceServer() {}
func (UnimplementedSwitchAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeSwitchAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchAgentServiceServer will
// result in compilation errors.
type UnsafeSwitchAgentServiceServer interface {
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

func RegisterSwitchAgentServiceServer(s grpc.ServiceRegistrar, srv SwitchAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedSwitchAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchAgentService_ServiceDesc, srv)
}

func _SwitchAgentService_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, req.(*FactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, req.(*GetReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchAgentService_ServiceDesc is the grpc.ServiceDesc for SwitchAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.SwitchAgentService",
	HandlerType: (*SwitchAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FactoryReset",
			Handler:    _SwitchAgentService_FactoryReset_Handler,
		},
		{
			MethodName: "GetReadiness",
			Handler:    _SwitchAgentService_GetReadiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sonic/v1alpha1/sonic.proto",
}
