apiVersion: wire.ironcore.dev/v1alpha1
kind: Cell
metadata:
  name: cell-sample
  namespace: default
spec:
  nodeRef:
    name: node-sample
  id: "100"
  hostname: switch-sample
  ips:
    - 10.0.0.1
    - 10.0.0.2
  prefixes:
    - 10.0.0.0/24
  peers:
    - interfaceRef:
        name: iface-sample
      dhcpRelay: 10.0.0.254
