name: Kustomize Validation

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  kustomize-validation:
    name: Run validate kustomizations
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Validate kustomizations
        run: make validate-kustomize
